### ISSUE TITLE
y limits not setting manually using plotSiberObject

### ISSUE THREAD

**Issue by AndrewLJackson** [AndrewLJackson/SIBER#41]

**Comment by AndrewLJackson** [comment]
this occurs because of this line 
if (any(is.null(x.limits), is.null(y.limits)))

**Comment by MarianneFalardeau** [comment]
I'm having the same issue with x.limits. I cannot set it up manually in the function plotSiberObject. How can it work? I tried many different ways of writing it, but the axis always remains the same.

I'm using this code:

plotSiberObject(siber.example,
                  ax.pad = 2, 
                  hulls = F, community.hulls.args, 
                  ellipses = T, group.ellipses.args,
                  group.hulls = F, group.hull.args,
                  bty = "L",
                  iso.order = c(1,2),
                  xlab = expression({delta}^13*C~'\u2030'),
                  ylab = expression({delta}^15*N~'\u2030'), 
                  x.limits = c(-26,-20))

The last part isn't working: x.limits = c(-26,-20)

Thanks!

Marianne

**Comment by AndrewLJackson** [comment]
Hi

A quick look at my code suggests you need to set y.limits also. Hopefully that will work. I will make a note and try to remember to fix it in the next release.

Best wisehs

Andrew

--

Dr Andrew Jackson, PhD, FTCD
Associate Professor
Irish Research Council Laureate
School of Natural Sciences, Department of Zoology
Trinity College Dublin, the University of Dublin
Dublin 2, Ireland.

+353 1 896 2728 | a.jackson@tcd.ie<mailto:a.jackson@tcd.ie>
Twitter: @yodacomplex<https://twitter.com/yodacomplex>
http://www.tcd.ie/Zoology/research/<http://www.tcd.ie/Zoology/research/groups/jackson/>groups/jackson/





On 7 Mar 2019, at 16:07, MarianneFalardeau <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm having the same issue with x.limits. I cannot set it up manually in the function plotSiberObject. How can it work? I tried many different ways of writing it, but the axis always remains the same.

I'm using this code:

plotSiberObject(siber.example,
ax.pad = 2,
hulls = F, community.hulls.args,
ellipses = T, group.ellipses.args,
group.hulls = F, group.hull.args,
bty = "L",
iso.order = c(1,2),
xlab = expression({delta}^13C~'\u2030'),
ylab = expression({delta}^15N~'\u2030'),
x.limits = c(-26,-20))

The last part isn't working: x.limits = c(-26,-20)

Thanks!

Marianne

**Comment by MarianneFalardeau** [comment]
Hi Andrew,

Unfortunately, I tried that too and it doesn't work either when I specify the y.limits. This doesn't work either:

plotSiberObject(siber.example,
                  ax.pad = 2, 
                  hulls = F, community.hulls.args, 
                  ellipses = T, group.ellipses.args,
                  group.hulls = F, group.hull.args,
                  bty = "L",
                  iso.order = c(1,2),
                  xlab = expression({delta}^13*C~'\u2030'),
                  ylab = expression({delta}^15*N~'\u2030'), 
                  x.limits = c(-26,-20),
                  y.limits = c(8,18))

**Comment by AndrewLJackson** [comment]
ive fixed this bug in the master branch. For v.2.1.4 specify both x.limits and y.limits to make it work. For v2.1.4.9999 onwards, this is fixed and you can specify one or the other or both. 

Install instructions for development version 

  ```R
    # install.packages("devtools") # install if necessary
    devtools::install_github("andrewljackson/SIBER@master",
    build_vignettes = TRUE)
    library(SIBER)
  ```

**Comment by MarianneFalardeau** [comment]
OK thanks, when I load the master I still get SIBER_2.1.4.9000 but maybe I need to wait a little bit for it to be updated?

**Comment by MarianneFalardeau** [comment]
It worked :)
